#safelist
branches:
  only:
    - master
    - develop

dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
    - "client/node_modules"

install: sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"

jobs:
  include:
    - stage: test
      script: nanobox run npm test
      if: branch IN (develop, master)

deploy: 
  - provider: script
    script: bash scripts/deploy_dev.sh
    on:
      branch: develop
  - provider: script
    script: bash scripts/deploy_prod.sh
    on:
      branch: master
