-- INSERT DATA
-- INSERT COUNTRY
INSERT INTO public.country VALUES (1, 'Andorra', 'AD');
INSERT INTO public.country VALUES (2, 'United Arab Emirates', 'AE');
INSERT INTO public.country VALUES (3, 'Afghanistan', 'AF');
INSERT INTO public.country VALUES (4, 'Antigua and Barbuda', 'AG');
INSERT INTO public.country VALUES (5, 'Anguilla', 'AI');
INSERT INTO public.country VALUES (6, 'Albania', 'AL');
INSERT INTO public.country VALUES (7, 'Armenia', 'AM');
INSERT INTO public.country VALUES (8, 'Angola', 'AO');
INSERT INTO public.country VALUES (9, 'Antarctica', 'AQ');
INSERT INTO public.country VALUES (10, 'Argentina', 'AR');
INSERT INTO public.country VALUES (11, 'American Samoa', 'AS');
INSERT INTO public.country VALUES (12, 'Austria', 'AT');
INSERT INTO public.country VALUES (13, 'Australia', 'AU');
INSERT INTO public.country VALUES (14, 'Aruba', 'AW');
INSERT INTO public.country VALUES (15, 'Åland', 'AX');
INSERT INTO public.country VALUES (16, 'Azerbaijan', 'AZ');
INSERT INTO public.country VALUES (17, 'Bosnia and Herzegovina', 'BA');
INSERT INTO public.country VALUES (18, 'Barbados', 'BB');
INSERT INTO public.country VALUES (19, 'Bangladesh', 'BD');
INSERT INTO public.country VALUES (20, 'Belgium', 'BE');
INSERT INTO public.country VALUES (21, 'Burkina Faso', 'BF');
INSERT INTO public.country VALUES (22, 'Bulgaria', 'BG');
INSERT INTO public.country VALUES (23, 'Bahrain', 'BH');
INSERT INTO public.country VALUES (24, 'Burundi', 'BI');
INSERT INTO public.country VALUES (25, 'Benin', 'BJ');
INSERT INTO public.country VALUES (26, 'Saint Barthélemy', 'BL');
INSERT INTO public.country VALUES (27, 'Bermuda', 'BM');
INSERT INTO public.country VALUES (28, 'Brunei', 'BN');
INSERT INTO public.country VALUES (29, 'Bolivia', 'BO');
INSERT INTO public.country VALUES (30, 'Bonaire', 'BQ');
INSERT INTO public.country VALUES (31, 'Brazil', 'BR');
INSERT INTO public.country VALUES (32, 'Bahamas', 'BS');
INSERT INTO public.country VALUES (33, 'Bhutan', 'BT');
INSERT INTO public.country VALUES (34, 'Bouvet Island', 'BV');
INSERT INTO public.country VALUES (35, 'Botswana', 'BW');
INSERT INTO public.country VALUES (36, 'Belarus', 'BY');
INSERT INTO public.country VALUES (37, 'Belize', 'BZ');
INSERT INTO public.country VALUES (38, 'Canada', 'CA');
INSERT INTO public.country VALUES (39, 'Cocos [Keeling] Islands', 'CC');
INSERT INTO public.country VALUES (40, 'Democratic Republic of the Congo', 'CD');
INSERT INTO public.country VALUES (41, 'Central African Republic', 'CF');
INSERT INTO public.country VALUES (42, 'Republic of the Congo', 'CG');
INSERT INTO public.country VALUES (43, 'Switzerland', 'CH');
INSERT INTO public.country VALUES (44, 'Ivory Coast', 'CI');
INSERT INTO public.country VALUES (45, 'Cook Islands', 'CK');
INSERT INTO public.country VALUES (46, 'Chile', 'CL');
INSERT INTO public.country VALUES (47, 'Cameroon', 'CM');
INSERT INTO public.country VALUES (48, 'China', 'CN');
INSERT INTO public.country VALUES (49, 'Colombia', 'CO');
INSERT INTO public.country VALUES (50, 'Costa Rica', 'CR');
INSERT INTO public.country VALUES (51, 'Cuba', 'CU');
INSERT INTO public.country VALUES (52, 'Cape Verde', 'CV');
INSERT INTO public.country VALUES (53, 'Curacao', 'CW');
INSERT INTO public.country VALUES (54, 'Christmas Island', 'CX');
INSERT INTO public.country VALUES (55, 'Cyprus', 'CY');
INSERT INTO public.country VALUES (56, 'Czechia', 'CZ');
INSERT INTO public.country VALUES (57, 'Germany', 'DE');
INSERT INTO public.country VALUES (58, 'Djibouti', 'DJ');
INSERT INTO public.country VALUES (59, 'Denmark', 'DK');
INSERT INTO public.country VALUES (60, 'Dominica', 'DM');
INSERT INTO public.country VALUES (61, 'Dominican Republic', 'DO');
INSERT INTO public.country VALUES (62, 'Algeria', 'DZ');
INSERT INTO public.country VALUES (63, 'Ecuador', 'EC');
INSERT INTO public.country VALUES (64, 'Estonia', 'EE');
INSERT INTO public.country VALUES (65, 'Egypt', 'EG');
INSERT INTO public.country VALUES (66, 'Western Sahara', 'EH');
INSERT INTO public.country VALUES (67, 'Eritrea', 'ER');
INSERT INTO public.country VALUES (68, 'Spain', 'ES');
INSERT INTO public.country VALUES (69, 'Ethiopia', 'ET');
INSERT INTO public.country VALUES (70, 'Finland', 'FI');
INSERT INTO public.country VALUES (71, 'Fiji', 'FJ');
INSERT INTO public.country VALUES (72, 'Falkland Islands', 'FK');
INSERT INTO public.country VALUES (73, 'Micronesia', 'FM');
INSERT INTO public.country VALUES (74, 'Faroe Islands', 'FO');
INSERT INTO public.country VALUES (75, 'France', 'FR');
INSERT INTO public.country VALUES (76, 'Gabon', 'GA');
INSERT INTO public.country VALUES (77, 'United Kingdom', 'GB');
INSERT INTO public.country VALUES (78, 'Grenada', 'GD');
INSERT INTO public.country VALUES (79, 'Georgia', 'GE');
INSERT INTO public.country VALUES (80, 'French Guiana', 'GF');
INSERT INTO public.country VALUES (81, 'Guernsey', 'GG');
INSERT INTO public.country VALUES (82, 'Ghana', 'GH');
INSERT INTO public.country VALUES (83, 'Gibraltar', 'GI');
INSERT INTO public.country VALUES (84, 'Greenland', 'GL');
INSERT INTO public.country VALUES (85, 'Gambia', 'GM');
INSERT INTO public.country VALUES (86, 'Guinea', 'GN');
INSERT INTO public.country VALUES (87, 'Guadeloupe', 'GP');
INSERT INTO public.country VALUES (88, 'Equatorial Guinea', 'GQ');
INSERT INTO public.country VALUES (89, 'Greece', 'GR');
INSERT INTO public.country VALUES (90, 'South Georgia and the South Sandwich Islands', 'GS');
INSERT INTO public.country VALUES (91, 'Guatemala', 'GT');
INSERT INTO public.country VALUES (92, 'Guam', 'GU');
INSERT INTO public.country VALUES (93, 'Guinea-Bissau', 'GW');
INSERT INTO public.country VALUES (94, 'Guyana', 'GY');
INSERT INTO public.country VALUES (95, 'Hong Kong', 'HK');
INSERT INTO public.country VALUES (96, 'Heard Island and McDonald Islands', 'HM');
INSERT INTO public.country VALUES (97, 'Honduras', 'HN');
INSERT INTO public.country VALUES (98, 'Croatia', 'HR');
INSERT INTO public.country VALUES (99, 'Haiti', 'HT');
INSERT INTO public.country VALUES (100, 'Hungary', 'HU');
INSERT INTO public.country VALUES (101, 'Indonesia', 'ID');
INSERT INTO public.country VALUES (102, 'Ireland', 'IE');
INSERT INTO public.country VALUES (103, 'Israel', 'IL');
INSERT INTO public.country VALUES (104, 'Isle of Man', 'IM');
INSERT INTO public.country VALUES (105, 'India', 'IN');
INSERT INTO public.country VALUES (106, 'British Indian Ocean Territory', 'IO');
INSERT INTO public.country VALUES (107, 'Iraq', 'IQ');
INSERT INTO public.country VALUES (108, 'Iran', 'IR');
INSERT INTO public.country VALUES (109, 'Iceland', 'IS');
INSERT INTO public.country VALUES (110, 'Italy', 'IT');
INSERT INTO public.country VALUES (111, 'Jersey', 'JE');
INSERT INTO public.country VALUES (112, 'Jamaica', 'JM');
INSERT INTO public.country VALUES (113, 'Jordan', 'JO');
INSERT INTO public.country VALUES (114, 'Japan', 'JP');
INSERT INTO public.country VALUES (115, 'Kenya', 'KE');
INSERT INTO public.country VALUES (116, 'Kyrgyzstan', 'KG');
INSERT INTO public.country VALUES (117, 'Cambodia', 'KH');
INSERT INTO public.country VALUES (118, 'Kiribati', 'KI');
INSERT INTO public.country VALUES (119, 'Comoros', 'KM');
INSERT INTO public.country VALUES (120, 'Saint Kitts and Nevis', 'KN');
INSERT INTO public.country VALUES (121, 'North Korea', 'KP');
INSERT INTO public.country VALUES (122, 'South Korea', 'KR');
INSERT INTO public.country VALUES (123, 'Kuwait', 'KW');
INSERT INTO public.country VALUES (124, 'Cayman Islands', 'KY');
INSERT INTO public.country VALUES (125, 'Kazakhstan', 'KZ');
INSERT INTO public.country VALUES (126, 'Laos', 'LA');
INSERT INTO public.country VALUES (127, 'Lebanon', 'LB');
INSERT INTO public.country VALUES (128, 'Saint Lucia', 'LC');
INSERT INTO public.country VALUES (129, 'Liechtenstein', 'LI');
INSERT INTO public.country VALUES (130, 'Sri Lanka', 'LK');
INSERT INTO public.country VALUES (131, 'Liberia', 'LR');
INSERT INTO public.country VALUES (132, 'Lesotho', 'LS');
INSERT INTO public.country VALUES (133, 'Lithuania', 'LT');
INSERT INTO public.country VALUES (134, 'Luxembourg', 'LU');
INSERT INTO public.country VALUES (135, 'Latvia', 'LV');
INSERT INTO public.country VALUES (136, 'Libya', 'LY');
INSERT INTO public.country VALUES (137, 'Morocco', 'MA');
INSERT INTO public.country VALUES (138, 'Monaco', 'MC');
INSERT INTO public.country VALUES (139, 'Moldova', 'MD');
INSERT INTO public.country VALUES (140, 'Montenegro', 'ME');
INSERT INTO public.country VALUES (141, 'Saint Martin', 'MF');
INSERT INTO public.country VALUES (142, 'Madagascar', 'MG');
INSERT INTO public.country VALUES (143, 'Marshall Islands', 'MH');
INSERT INTO public.country VALUES (144, 'Macedonia', 'MK');
INSERT INTO public.country VALUES (145, 'Mali', 'ML');
INSERT INTO public.country VALUES (146, 'Myanmar [Burma]', 'MM');
INSERT INTO public.country VALUES (147, 'Mongolia', 'MN');
INSERT INTO public.country VALUES (148, 'Macao', 'MO');
INSERT INTO public.country VALUES (149, 'Northern Mariana Islands', 'MP');
INSERT INTO public.country VALUES (150, 'Martinique', 'MQ');
INSERT INTO public.country VALUES (151, 'Mauritania', 'MR');
INSERT INTO public.country VALUES (152, 'Montserrat', 'MS');
INSERT INTO public.country VALUES (153, 'Malta', 'MT');
INSERT INTO public.country VALUES (154, 'Mauritius', 'MU');
INSERT INTO public.country VALUES (155, 'Maldives', 'MV');
INSERT INTO public.country VALUES (156, 'Malawi', 'MW');
INSERT INTO public.country VALUES (157, 'Mexico', 'MX');
INSERT INTO public.country VALUES (158, 'Malaysia', 'MY');
INSERT INTO public.country VALUES (159, 'Mozambique', 'MZ');
INSERT INTO public.country VALUES (160, 'Namibia', 'NA');
INSERT INTO public.country VALUES (161, 'New Caledonia', 'NC');
INSERT INTO public.country VALUES (162, 'Niger', 'NE');
INSERT INTO public.country VALUES (163, 'Norfolk Island', 'NF');
INSERT INTO public.country VALUES (164, 'Nigeria', 'NG');
INSERT INTO public.country VALUES (165, 'Nicaragua', 'NI');
INSERT INTO public.country VALUES (166, 'Netherlands', 'NL');
INSERT INTO public.country VALUES (167, 'Norway', 'NO');
INSERT INTO public.country VALUES (168, 'Nepal', 'NP');
INSERT INTO public.country VALUES (169, 'Nauru', 'NR');
INSERT INTO public.country VALUES (170, 'Niue', 'NU');
INSERT INTO public.country VALUES (171, 'New Zealand', 'NZ');
INSERT INTO public.country VALUES (172, 'Oman', 'OM');
INSERT INTO public.country VALUES (173, 'Panama', 'PA');
INSERT INTO public.country VALUES (174, 'Peru', 'PE');
INSERT INTO public.country VALUES (175, 'French Polynesia', 'PF');
INSERT INTO public.country VALUES (176, 'Papua New Guinea', 'PG');
INSERT INTO public.country VALUES (177, 'Philippines', 'PH');
INSERT INTO public.country VALUES (178, 'Pakistan', 'PK');
INSERT INTO public.country VALUES (179, 'Poland', 'PL');
INSERT INTO public.country VALUES (180, 'Saint Pierre and Miquelon', 'PM');
INSERT INTO public.country VALUES (181, 'Pitcairn Islands', 'PN');
INSERT INTO public.country VALUES (182, 'Puerto Rico', 'PR');
INSERT INTO public.country VALUES (183, 'Palestine', 'PS');
INSERT INTO public.country VALUES (184, 'Portugal', 'PT');
INSERT INTO public.country VALUES (185, 'Palau', 'PW');
INSERT INTO public.country VALUES (186, 'Paraguay', 'PY');
INSERT INTO public.country VALUES (187, 'Qatar', 'QA');
INSERT INTO public.country VALUES (188, 'Réunion', 'RE');
INSERT INTO public.country VALUES (189, 'Romania', 'RO');
INSERT INTO public.country VALUES (190, 'Serbia', 'RS');
INSERT INTO public.country VALUES (191, 'Russia', 'RU');
INSERT INTO public.country VALUES (192, 'Rwanda', 'RW');
INSERT INTO public.country VALUES (193, 'Saudi Arabia', 'SA');
INSERT INTO public.country VALUES (194, 'Solomon Islands', 'SB');
INSERT INTO public.country VALUES (195, 'Seychelles', 'SC');
INSERT INTO public.country VALUES (196, 'Sudan', 'SD');
INSERT INTO public.country VALUES (197, 'Sweden', 'SE');
INSERT INTO public.country VALUES (198, 'Singapore', 'SG');
INSERT INTO public.country VALUES (199, 'Saint Helena', 'SH');
INSERT INTO public.country VALUES (200, 'Slovenia', 'SI');
INSERT INTO public.country VALUES (201, 'Svalbard and Jan Mayen', 'SJ');
INSERT INTO public.country VALUES (202, 'Slovakia', 'SK');
INSERT INTO public.country VALUES (203, 'Sierra Leone', 'SL');
INSERT INTO public.country VALUES (204, 'San Marino', 'SM');
INSERT INTO public.country VALUES (205, 'Senegal', 'SN');
INSERT INTO public.country VALUES (206, 'Somalia', 'SO');
INSERT INTO public.country VALUES (207, 'Suriname', 'SR');
INSERT INTO public.country VALUES (208, 'South Sudan', 'SS');
INSERT INTO public.country VALUES (209, 'São Tomé and Príncipe', 'ST');
INSERT INTO public.country VALUES (210, 'El Salvador', 'SV');
INSERT INTO public.country VALUES (211, 'Sint Maarten', 'SX');
INSERT INTO public.country VALUES (212, 'Syria', 'SY');
INSERT INTO public.country VALUES (213, 'Swaziland', 'SZ');
INSERT INTO public.country VALUES (214, 'Turks and Caicos Islands', 'TC');
INSERT INTO public.country VALUES (215, 'Chad', 'TD');
INSERT INTO public.country VALUES (216, 'French Southern Territories', 'TF');
INSERT INTO public.country VALUES (217, 'Togo', 'TG');
INSERT INTO public.country VALUES (218, 'Thailand', 'TH');
INSERT INTO public.country VALUES (219, 'Tajikistan', 'TJ');
INSERT INTO public.country VALUES (220, 'Tokelau', 'TK');
INSERT INTO public.country VALUES (221, 'East Timor', 'TL');
INSERT INTO public.country VALUES (222, 'Turkmenistan', 'TM');
INSERT INTO public.country VALUES (223, 'Tunisia', 'TN');
INSERT INTO public.country VALUES (224, 'Tonga', 'TO');
INSERT INTO public.country VALUES (225, 'Turkey', 'TR');
INSERT INTO public.country VALUES (226, 'Trinidad and Tobago', 'TT');
INSERT INTO public.country VALUES (227, 'Tuvalu', 'TV');
INSERT INTO public.country VALUES (228, 'Taiwan', 'TW');
INSERT INTO public.country VALUES (229, 'Tanzania', 'TZ');
INSERT INTO public.country VALUES (230, 'Ukraine', 'UA');
INSERT INTO public.country VALUES (231, 'Uganda', 'UG');
INSERT INTO public.country VALUES (232, 'U.S. Minor Outlying Islands', 'UM');
INSERT INTO public.country VALUES (233, 'United States', 'US');
INSERT INTO public.country VALUES (234, 'Uruguay', 'UY');
INSERT INTO public.country VALUES (235, 'Uzbekistan', 'UZ');
INSERT INTO public.country VALUES (236, 'Vatican City', 'VA');
INSERT INTO public.country VALUES (237, 'Saint Vincent and the Grenadines', 'VC');
INSERT INTO public.country VALUES (238, 'Venezuela', 'VE');
INSERT INTO public.country VALUES (239, 'British Virgin Islands', 'VG');
INSERT INTO public.country VALUES (240, 'U.S. Virgin Islands', 'VI');
INSERT INTO public.country VALUES (241, 'Vietnam', 'VN');
INSERT INTO public.country VALUES (242, 'Vanuatu', 'VU');
INSERT INTO public.country VALUES (243, 'Wallis and Futuna', 'WF');
INSERT INTO public.country VALUES (244, 'Samoa', 'WS');
INSERT INTO public.country VALUES (245, 'Kosovo', 'XK');
INSERT INTO public.country VALUES (246, 'Yemen', 'YE');
INSERT INTO public.country VALUES (247, 'Mayotte', 'YT');
INSERT INTO public.country VALUES (248, 'South Africa', 'ZA');
INSERT INTO public.country VALUES (249, 'Zambia', 'ZM');
INSERT INTO public.country VALUES (250, 'Zimbabwe', 'ZW');
-- /INSERT COUNTRY
-- /INSERT DATA

